version: '3.8'

services:
  tensorflow-server:
    image: tensorflow/serving:latest
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - ./basic_model:/models/basic_model

    command: tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=basic_model --model_base_path=/models/basic_model
